api_token: 123456
test: <%= 1 + 1 %>
request_all_pages: false
fields:
  person:
    middle_name: 123abc
    custom_field: 99912a
  deal:
    age: 987cba
    stage: 456sdf
field_values:
  person:
    custom_field:
      99: custom_value
    interview_quality:
      66: Amazing
      65: Good
  deal:
    stage:
      23: 1st Contact

