api_token:
test: <%= 1 + 1 %>
request_all_pages: true
fields:
  person:
    middle_name: 123abc
  deal:
    age: 987cba
field_values:
  person:
    interview_quality:
      66: Amazing
      65: Good

